coverage_service: cobertura_xml
xcodeproj: iOSGitHubActions.xcodeproj
input_format: profdata
output_directory: Coverage/
build_directory: build/Build/
scheme: iOSGitHubActions
ignore:
  - iOSGitHubActionsTests/*